import {MigrationInterface, QueryRunner} from "typeorm";

export class Initialise1647437416565 implements MigrationInterface {
    name = 'Initialise1647437416565'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "certification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "certificate" character varying NOT NULL, "subject" character varying NOT NULL, "description" character varying NOT NULL, "issuedBy" character varying NOT NULL, "badgeUrl" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_a7364bd3e4a407f67d8165b820c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."diploma_type_enum" AS ENUM('Teaching_Degree', 'Subject_Degree', 'Other')`);
        await queryRunner.query(`CREATE TABLE "diploma" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "degree" character varying NOT NULL, "type" "public"."diploma_type_enum" NOT NULL DEFAULT 'Teaching_Degree', "university" character varying NOT NULL, "specialization" character varying NOT NULL, "badgeUrl" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_17fdb808898615d3fb807644165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_status_enum" AS ENUM('pending', 'accepted', 'canceled', 'finished')`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_type_enum" AS ENUM('one-to-one', 'group', 'trial')`);
        await queryRunner.query(`CREATE TABLE "schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tutorId" uuid NOT NULL, "startTime" TIMESTAMP WITH TIME ZONE NOT NULL, "endTime" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."schedule_status_enum" NOT NULL DEFAULT 'pending', "type" "public"."schedule_type_enum" NOT NULL DEFAULT 'one-to-one', "recurrenceRule" character varying NOT NULL, "subject" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1c05e42aec7371641193e180046" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_balance_unit_enum" AS ENUM('VND', 'USD', 'EUR')`);
        await queryRunner.query(`CREATE TABLE "user_balance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ammount" numeric(15,5) NOT NULL, "unit" "public"."user_balance_unit_enum" NOT NULL DEFAULT 'VND', "hourNumber" integer NOT NULL DEFAULT '0', "discount" integer NOT NULL DEFAULT '0', "tutorId" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f3edf5a1907e7b430421b9c2ddd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_gender_enum" AS ENUM('Male', 'Female')`);
        await queryRunner.query(`CREATE TABLE "user_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gender" "public"."user_profile_gender_enum" NOT NULL DEFAULT 'Male', "timezone" character varying NOT NULL, "age" integer, "address" character varying NOT NULL DEFAULT '', "country" character varying NOT NULL, "avatar" character varying NOT NULL DEFAULT 'https://pic.onlinewebfonts.com/svg/img_264570.png', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f44d0cd18cfd80b0fed7806c3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tutorId" uuid NOT NULL, "subject" character varying NOT NULL, "content" character varying NOT NULL, "score" integer NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "speciality_tutor" ("tutorId" uuid NOT NULL, "specialityId" uuid NOT NULL, CONSTRAINT "PK_2b7af7057a4bec7ae7ce49f8f5c" PRIMARY KEY ("tutorId", "specialityId"))`);
        await queryRunner.query(`CREATE TABLE "speciality" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "subjectId" uuid NOT NULL, "numberOfTutors" integer NOT NULL DEFAULT '0', "description" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cfdbcfa372a34f2d9c1d5180052" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_balance_unit_enum" AS ENUM('VND', 'USD', 'EUR')`);
        await queryRunner.query(`CREATE TABLE "tutor_balance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ammount" numeric(15,5) NOT NULL DEFAULT '0', "unit" "public"."tutor_balance_unit_enum" NOT NULL DEFAULT 'VND', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_812388dc3c196aaf93cea27b025" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_profile_gender_enum" AS ENUM('Male', 'Female')`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_profile_advancenotice_enum" AS ENUM('at_least_1_hour', 'at_least_3_hour', 'at_least_6_hour', 'at_least_12_hour', 'at_least_1_day', 'at_least_2_day')`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_profile_bookingwindow_enum" AS ENUM('2_week', '3_week', '1_month', '2_month')`);
        await queryRunner.query(`CREATE TABLE "tutor_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bio" character varying NOT NULL DEFAULT '', "gender" "public"."tutor_profile_gender_enum" NOT NULL DEFAULT 'Male', "age" integer, "address" character varying NOT NULL DEFAULT '', "country" character varying NOT NULL, "videoUrl" character varying NOT NULL, "timezone" character varying NOT NULL, "avatar" character varying NOT NULL DEFAULT 'https://pic.onlinewebfonts.com/svg/img_264570.png', "advanceNotice" "public"."tutor_profile_advancenotice_enum" NOT NULL DEFAULT 'at_least_1_day', "bookingWindow" "public"."tutor_profile_bookingwindow_enum" NOT NULL DEFAULT '2_week', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0cc3e6db6aeecc65adda6e0e7ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "startTime" integer NOT NULL, "endTime" integer NOT NULL, "dayOfWeek" integer NOT NULL, CONSTRAINT "PK_05a8158cf1112294b1c86e7f1d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certification_application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "certificate" character varying NOT NULL, "subject" character varying NOT NULL, "description" character varying NOT NULL, "issuedBy" character varying NOT NULL, "badgeUrl" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_8a6d4de22aa4ae19691fab45f35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."diploma_application_type_enum" AS ENUM('Teaching_Degree', 'Subject_Degree', 'Other')`);
        await queryRunner.query(`CREATE TABLE "diploma_application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "degree" character varying NOT NULL, "type" "public"."diploma_application_type_enum" NOT NULL DEFAULT 'Teaching_Degree', "university" character varying NOT NULL, "specialization" character varying NOT NULL, "badgeUrl" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_e71f28ae49490c17669a22133c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_application_gender_enum" AS ENUM('Male', 'Female')`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_application_advancenotice_enum" AS ENUM('at_least_1_hour', 'at_least_3_hour', 'at_least_6_hour', 'at_least_12_hour', 'at_least_1_day', 'at_least_2_day')`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_application_bookingwindow_enum" AS ENUM('2_week', '3_week', '1_month', '2_month')`);
        await queryRunner.query(`CREATE TABLE "tutor_application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "fullName" character varying NOT NULL, "subjectId" uuid, "salary" integer, "bio" character varying NOT NULL DEFAULT '', "gender" "public"."tutor_application_gender_enum" NOT NULL DEFAULT 'Male', "country" character varying, "videoUrl" character varying, "avatar" character varying NOT NULL DEFAULT 'https://pic.onlinewebfonts.com/svg/img_264570.png', "advanceNotice" "public"."tutor_application_advancenotice_enum" NOT NULL DEFAULT 'at_least_1_day', "bookingWindow" "public"."tutor_application_bookingwindow_enum" NOT NULL DEFAULT '2_week', "age" integer, "address" character varying NOT NULL DEFAULT '', "timezone" character varying, "isValid" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_3f639670c00626c7dc7f3e575e0" UNIQUE ("username"), CONSTRAINT "UQ_24ba548274996c58253736094d7" UNIQUE ("email"), CONSTRAINT "UQ_18254e1c2aa7f7c7b6cd49f539e" UNIQUE ("password"), CONSTRAINT "PK_640b694fd0186a58d7c811eb195" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" uuid NOT NULL, "startTime" integer NOT NULL, "endTime" integer NOT NULL, "dayOfWeek" integer NOT NULL, CONSTRAINT "PK_c597714f7043b890e398b6bd6a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "tutorId" uuid NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject" character varying NOT NULL, "userId" character varying NOT NULL, "title" character varying NOT NULL, "content" character varying NOT NULL, "lowestPrice" integer NOT NULL, "highestPrice" integer NOT NULL, "description" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_167d324701e6867f189aed52e18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."resume_type_enum" AS ENUM('Education', 'Work Experience', 'Certification')`);
        await queryRunner.query(`CREATE TABLE "resume" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tutorId" character varying NOT NULL, "title" character varying NOT NULL, "type" "public"."resume_type_enum" NOT NULL DEFAULT 'Certification', "description" character varying NOT NULL, "startYear" integer NOT NULL, "endYear" integer, CONSTRAINT "PK_7ff05ea7599e13fac01ac812e48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "level" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a0d33334424e64fb78dc3ce7196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "isOnline" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "profileId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_9466682df91534dd95e4dbaa616" UNIQUE ("profileId")`);
        await queryRunner.query(`ALTER TABLE "user" ADD "balanceId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_122eba7abb932493831f1e0f62b" UNIQUE ("balanceId")`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "isOnline" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "profileId" uuid`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD CONSTRAINT "UQ_c0a68fd48f16be59eb3cf2d5382" UNIQUE ("profileId")`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "balanceId" uuid`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD CONSTRAINT "UQ_aa871906927d9be7623114b4f42" UNIQUE ("balanceId")`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "certification" ADD CONSTRAINT "FK_6fefd01b1f182a11ad91574b879" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diploma" ADD CONSTRAINT "FK_290182e472cdb4f072fadf2e528" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_56604413fff7f049b6dff722eed" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_d796103491cf0bae197dda59477" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9466682df91534dd95e4dbaa616" FOREIGN KEY ("profileId") REFERENCES "user_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_122eba7abb932493831f1e0f62b" FOREIGN KEY ("balanceId") REFERENCES "user_balance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_8dc9c3a13e1e099d799ad593b40" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_1337f93918c70837d3cea105d39" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speciality_tutor" ADD CONSTRAINT "FK_856947e52bcfd96907d9b3b2cab" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speciality_tutor" ADD CONSTRAINT "FK_091966556db7d83464256ef11c7" FOREIGN KEY ("specialityId") REFERENCES "speciality"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD CONSTRAINT "FK_c0a68fd48f16be59eb3cf2d5382" FOREIGN KEY ("profileId") REFERENCES "tutor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD CONSTRAINT "FK_aa871906927d9be7623114b4f42" FOREIGN KEY ("balanceId") REFERENCES "tutor_balance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability" ADD CONSTRAINT "FK_a2dbcbd86709186ad2a92fd63ae" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certification_application" ADD CONSTRAINT "FK_550720e900742e783d65d63a537" FOREIGN KEY ("tutorId") REFERENCES "tutor_application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diploma_application" ADD CONSTRAINT "FK_22ad8343ad37113b17df9cd6fd5" FOREIGN KEY ("tutorId") REFERENCES "tutor_application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_application" ADD CONSTRAINT "FK_580cd366b18f4601e4c3942dd5c" FOREIGN KEY ("tutorId") REFERENCES "tutor_application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_d0bf2b28f974f68f2b9e3e97274" FOREIGN KEY ("tutorId") REFERENCES "tutor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_d0bf2b28f974f68f2b9e3e97274"`);
        await queryRunner.query(`ALTER TABLE "availability_application" DROP CONSTRAINT "FK_580cd366b18f4601e4c3942dd5c"`);
        await queryRunner.query(`ALTER TABLE "diploma_application" DROP CONSTRAINT "FK_22ad8343ad37113b17df9cd6fd5"`);
        await queryRunner.query(`ALTER TABLE "certification_application" DROP CONSTRAINT "FK_550720e900742e783d65d63a537"`);
        await queryRunner.query(`ALTER TABLE "availability" DROP CONSTRAINT "FK_a2dbcbd86709186ad2a92fd63ae"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP CONSTRAINT "FK_aa871906927d9be7623114b4f42"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP CONSTRAINT "FK_c0a68fd48f16be59eb3cf2d5382"`);
        await queryRunner.query(`ALTER TABLE "speciality_tutor" DROP CONSTRAINT "FK_091966556db7d83464256ef11c7"`);
        await queryRunner.query(`ALTER TABLE "speciality_tutor" DROP CONSTRAINT "FK_856947e52bcfd96907d9b3b2cab"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_1337f93918c70837d3cea105d39"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_8dc9c3a13e1e099d799ad593b40"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_122eba7abb932493831f1e0f62b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9466682df91534dd95e4dbaa616"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_d796103491cf0bae197dda59477"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_56604413fff7f049b6dff722eed"`);
        await queryRunner.query(`ALTER TABLE "diploma" DROP CONSTRAINT "FK_290182e472cdb4f072fadf2e528"`);
        await queryRunner.query(`ALTER TABLE "certification" DROP CONSTRAINT "FK_6fefd01b1f182a11ad91574b879"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP CONSTRAINT "UQ_aa871906927d9be7623114b4f42"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "balanceId"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP CONSTRAINT "UQ_c0a68fd48f16be59eb3cf2d5382"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "profileId"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "isOnline"`);
        await queryRunner.query(`ALTER TABLE "tutor" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_122eba7abb932493831f1e0f62b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "balanceId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_9466682df91534dd95e4dbaa616"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "profileId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isOnline"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tutor" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "skill"`);
        await queryRunner.query(`DROP TABLE "resume"`);
        await queryRunner.query(`DROP TYPE "public"."resume_type_enum"`);
        await queryRunner.query(`DROP TABLE "request"`);
        await queryRunner.query(`DROP TABLE "course"`);
        await queryRunner.query(`DROP TABLE "availability_application"`);
        await queryRunner.query(`DROP TABLE "tutor_application"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_application_bookingwindow_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_application_advancenotice_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_application_gender_enum"`);
        await queryRunner.query(`DROP TABLE "diploma_application"`);
        await queryRunner.query(`DROP TYPE "public"."diploma_application_type_enum"`);
        await queryRunner.query(`DROP TABLE "certification_application"`);
        await queryRunner.query(`DROP TABLE "availability"`);
        await queryRunner.query(`DROP TABLE "tutor_profile"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_profile_bookingwindow_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_profile_advancenotice_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_profile_gender_enum"`);
        await queryRunner.query(`DROP TABLE "tutor_balance"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_balance_unit_enum"`);
        await queryRunner.query(`DROP TABLE "speciality"`);
        await queryRunner.query(`DROP TABLE "speciality_tutor"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TABLE "user_profile"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_gender_enum"`);
        await queryRunner.query(`DROP TABLE "user_balance"`);
        await queryRunner.query(`DROP TYPE "public"."user_balance_unit_enum"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_status_enum"`);
        await queryRunner.query(`DROP TABLE "diploma"`);
        await queryRunner.query(`DROP TYPE "public"."diploma_type_enum"`);
        await queryRunner.query(`DROP TABLE "certification"`);
    }

}
